import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./_component/navBar";
// import Input from "./input/page";
import DataProvider from "./_component/DataProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>){
  
  return (
    <html lang="en">

      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >

        <DataProvider>
         <header className="bg-gradient-to-r from-red-500 to-pink-500 text-white ">
            <div className="flex justify-between items-center max-w-7xl mx-auto px-6 py-6">
              <h1 className="text-2xl sm:text-3xl font-extrabold tracking-wide hover:tracking-wider transition-all duration-300">
               Next.js App
            </h1>
            <div>
                <NavBar />
              </div>
            </div>
        </header>


        <div className="">
           {children}
        </div>
       
        <footer className="bg-blue-600 py-[3rem] ">
            <div className="max-w-7xl  mx-auto text-center">
                <p className="text-[1.3rem]">&copy;2025 All copy Rights Reserved | ❤️ Developed by Next.js developer</p>
            </div>
        </footer>
        </DataProvider>

      </body>
    </html>
  );
}
